<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-11T23:42:47Z" name="Suite" finished-at="2019-06-11T23:43:15Z" duration-ms="28164">
    <groups>
    </groups>
    <test started-at="2019-06-11T23:42:47Z" name="Test" finished-at="2019-06-11T23:43:15Z" duration-ms="28164">
      <class name="testCases.TestCase1">
        <test-method signature="testCase001()" started-at="2019-06-11T23:42:47Z" name="testCase001" finished-at="2019-06-11T23:42:57Z" duration-ms="9833" status="PASS">
        </test-method>
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)" started-at="2019-06-11T23:42:57Z" name="getResult" finished-at="2019-06-11T23:42:57Z" duration-ms="25" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult: testCase001 STATUS:SUCCESS METHOD:testCases.TestCase1.testCase001()]
]]>
              </value>
            </param>
          </params>
        </test-method>
        <test-method signature="testCase002()" started-at="2019-06-11T23:42:57Z" name="testCase002" finished-at="2019-06-11T23:43:06Z" duration-ms="9410" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at org.testng.Assert.assertEquals(Assert.java:291)
	at testCases.TestCase1.testCase002(TestCase1.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)" started-at="2019-06-11T23:43:06Z" name="getResult" finished-at="2019-06-11T23:43:07Z" duration-ms="493" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult: testCase002 STATUS:FAILURE METHOD:testCases.TestCase1.testCase002()]
]]>
              </value>
            </param>
          </params>
        </test-method>
      </class>
      <class name="testCases.TestCase2">
        <test-method is-config="true" signature="startReport()" started-at="2019-06-11T23:42:47Z" name="startReport" finished-at="2019-06-11T23:42:47Z" duration-ms="139" status="PASS">
        </test-method>
        <test-method signature="testCase003()" started-at="2019-06-11T23:43:07Z" name="testCase003" finished-at="2019-06-11T23:43:15Z" duration-ms="8380" status="PASS">
        </test-method>
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)" started-at="2019-06-11T23:43:15Z" name="getResult" finished-at="2019-06-11T23:43:15Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult: testCase003 STATUS:SUCCESS METHOD:testCases.TestCase2.testCase003()]
]]>
              </value>
            </param>
          </params>
        </test-method>
        <test-method is-config="true" signature="tearDown()" started-at="2019-06-11T23:43:15Z" name="tearDown" finished-at="2019-06-11T23:43:15Z" duration-ms="459" status="PASS">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
